# Generated by Django 4.1.6 on 2023-03-11 16:51

import assignments.models.assignments
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('assignment_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_open', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('io_file', models.FileField(blank=True, null=True, upload_to=assignments.models.assignments.Assignment.update_filename, validators=[utils.validators.validate_io_file])),
                ('classes', models.ManyToManyField(blank=True, related_name='assignments', to='accounts.class')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('lang', models.CharField(default='', max_length=50)),
                ('status', models.CharField(blank=True, default='UnAccepted', max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('due_date'))), name='assignment_start_lte_due'),
        ),
    ]
