# Generated by Django 4.1.6 on 2023-04-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_class_students'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='classes',
        ),
        migrations.AddField(
            model_name='assignment',
            name='classes',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.class'),
            preserve_default=False,
        ),
    ]
