# Generated by Django 4.1.6 on 2023-04-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_class_students'),
        ('assignments', '0002_remove_assignment_classes_assignment_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='classes',
        ),
        migrations.AddField(
            model_name='assignment',
            name='in_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.class'),
        ),
    ]
