# Generated by Django 4.0 on 2023-04-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_remove_assignment_classes_assignment_in_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, default='Unaccepted', max_length=10, null=True),
        ),
    ]
