# Generated by Django 4.1.6 on 2023-04-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_submission_submission_score_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='langs',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='assignments.lang'),
        ),
    ]
