# Generated by Django 4.1.6 on 2023-04-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_lang_assignment_langs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, default='Unaccepted', max_length=50, null=True),
        ),
    ]
