# Generated by Django 4.1.6 on 2023-04-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lang',
            name='display',
            field=models.CharField(default=models.CharField(max_length=50, unique=True), max_length=50),
        ),
        migrations.AlterField(
            model_name='lang',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
