# Generated by Django 4.1.6 on 2023-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_lang_display_alter_lang_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='display',
            field=models.CharField(default='', max_length=50),
        ),
    ]
