# Generated by Django 4.1.6 on 2023-04-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_class_langs'),
        ('assignments', '0010_alter_lang_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='in_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.class'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('in_class', 'assignment_code')},
        ),
    ]
