# Generated by Django 4.1.6 on 2023-04-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_alter_assignment_assignment_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lang',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
