# Generated by Django 4.1.6 on 2023-04-09 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='studies_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
