# Generated by Django 4.1.6 on 2023-04-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_class_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
